### ISSUE TITLE
Roomtemperature vs Floortemperature

### ISSUE THREAD

**Issue by erimsby** [dhutchison/homebridge-ebeco#11]
**Is your feature request related to a problem? Please describe:**
Roomtemperature is more relevant to me since I have my Ebeco installation in a 40m2 living room as main heating source. 

**Describe the solution you'd like:**
I'd like to be able to switch to use room temperature instead of floor temperature. 

**Describe alternatives you've considered:**
In my case alternative to homebridge. 

**Additional context:**

**Comment by dhutchison** [comment]
Should be simple enough to add a config option to support that. 

I'll take a look later in the week. 

Just needs a config option and a change to the get current temperature method of src/platformAccessory.ts

**Comment by erimsby** [comment]
Thank you David. I really appreciate that!

Den mån 15 mars 2021 kl 22:34 skrev David Hutchison <
***@***.***>:

**Comment by dhutchison** [comment]
v0.2.0 should be available shortly. 

Adds a new temperatureSensor setting with possible values "room" and "floor".

**Comment by DanielK-Ocean** [comment]
Thanks for a great plugin! 
The dashboard still display room temperature when "temperatureSensor": "floor", is set. Any quick fix to this?

**Comment by DanielK-Ocean** [comment]
Sorry, I could just remove the "temperatureSensor": "floor" from config and it will display the floor temperature instead of room temp.
